### ISSUE TITLE
3. Submitting Student Form

### ISSUE THREAD

**Issue by akbelcolak** [akbelcolak/language-platform#6]
As a language learner, I can create an account by submitting the form.

acceptance criteria:
- [ ] I can fill the form and submit it.
- [ ] I have to fill obligatory areas which are:
 * Email
 * password 
 * location
 * language to learn 
 * username
otherwise, I will get an error message.
- [ ]  if I have registered with my email before I cannot use my email for another user registration.
if so I will get an error message.

**Comment by mmelcot** [comment]
2: "_... obligatory areas_": you have to mention here which one they are, so that the developer will know what to code :wink: 

3: You should explain concretly what happens if a user wants to create an account with an email which already exists. For instance: "_If a user creates an account with an email which is already registered in the system, an error page will show_"

**Comment by akbelcolak** [comment]
I have added which obligatory areas should be in the form. And also what happens if a user tries to use the same email address more than one time

**Comment by akbelcolak** [comment]
this user story has 2 parts
1. a form made in React
2. connecting with database to save the info and recieve the info.
